spring:
  profiles:
    active: native
  mvc:
    pathmatch:
      matching-stratedy: ant-path-matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: vasco
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
mail:
  host: smtp.gmail.com
  port: 587
  username: desafioedussincdiamond@gmail.com
  password: yiaveplfxyrrugvd
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true